sudo: required

services:
  - docker

stages:
  - alpine
  - services
  - services-dev
  - promote

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

jobs:
  include:

    - stage: alpine
      before_script:
        - make travis-alpine-before_script
      script:
        - make travis-alpine-script
      after_success:
        - make travis-alpine-after_success

    - stage: services
      env:
        - SERVICE=nginx
      before_script:
        - make travis-nginx-before_script
      script:
        - make travis-nginx-script
      after_success:
        - make travis-nginx-after_success

    - stage: services
      env:
        - SERVICE=php-cli
      before_script:
        - make travis-php-cli-before_script
      script:
        - make travis-php-cli-script
      after_success:
        - make travis-php-cli-after_success

    - stage: services
      env:
        - SERVICE=php-fpm
      before_script:
        - make travis-php-fpm-before_script
      script:
        - make travis-php-fpm-script
      after_success:
        - make travis-php-fpm-after_success

    - stage: services-dev
      env:
        - SERVICE=php-cli-dev
      before_script:
        - make travis-php-cli-dev-before_script
      script:
        - make travis-php-cli-dev-script
      after_success:
        - make travis-php-cli-dev-after_success

    - stage: services-dev
      env:
        - SERVICE=php-fpm-dev
      before_script:
        - make travis-php-fpm-dev-before_script
      script:
        - make travis-php-fpm-dev-script
      after_success:
        - make travis-php-fpm-dev-after_success

    - stage: promote
      env:
        - SERVICE=alpine
      before_script:
        - make travis-promote-before_script
      script:
        - make travis-promote-script

    - stage: promote
      env:
        - SERVICE=nginx
      before_script:
        - make travis-promote-before_script
      script:
        - make travis-promote-script

    - stage: promote
      env:
        - SERVICE=php-cli
      before_script:
        - make travis-promote-before_script
      script:
        - make travis-promote-script

    - stage: promote
      env:
        - SERVICE=php-cli-dev
      before_script:
        - make travis-promote-before_script
      script:
        - make travis-promote-script

    - stage: promote
      env:
        - SERVICE=php-fpm
      before_script:
        - make travis-promote-before_script
      script:
        - make travis-promote-script

    - stage: promote
      env:
        - SERVICE=php-fpm-dev
      before_script:
        - make travis-promote-before_script
      script:
        - make travis-promote-script

notifications:
  webhooks:
    - https://h2a-hubot.herokuapp.com/webhooks/travis
